version: '3.8'

services:
  php:
    build: ./docker
    container_name: php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/:/var/www/html/public
      - ./docker/www_logs/nginx:/var/log/nginx
    depends_on:
      - php
      - db
      - qdrant

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./:/qdrant/storage:z

volumes:
  db_data:
